export const GET_RECORDS = "GET_RECORDS";
export const SHOW_RECORDS_ERROR = "SHOW_RECORDS_ERROR";
export const SEARCH_RECORDS = "SEARCH_RECORDS";
export const SET_LOADING = "SET_LOADING";
export const SET_SELECTED_GENDER = "SET_SELECTED_GENDER";
export const FILTER_BY_GENDER = "FILTER_BY_GENDER";
export const FILTER_BY_CREDIT_CARD = "FILTER_BY_CREDIT_CARD";
export const SET_RECORDS_PER_PAGE = "SET_RECORDS_PER_PAGE";
