export const GET_RECORDS = "GET_RECORDS";
export const SHOW_RECORDS_ERROR = "SHOW_RECORDS_ERROR";
export const SEARCH_RECORDS = "SEARCH_RECORDS";
export const SET_LOADING = "SET_LOADING";
export const GENDER_FILTER = "GENDER_FILTER";
export const CREDIT_CARD_FILTER = "CREDIT_CARD_FILTER";
export const SET_RECORDS_PER_PAGE = "SET_RECORDS_PER_PAGE";
